CREATE TABLE "FallbackRegisterBalance" (
  "registerId" TEXT NOT NULL PRIMARY KEY,
  "cashSales" DECIMAL(14,2) NOT NULL DEFAULT 0,
  "cashTopups" DECIMAL(14,2) NOT NULL DEFAULT 0,
  "cashRefunds" DECIMAL(14,2) NOT NULL DEFAULT 0,
  "cashPaidOut" DECIMAL(14,2) NOT NULL DEFAULT 0,
  "cashIn" DECIMAL(14,2) NOT NULL DEFAULT 0,
  "cashOut" DECIMAL(14,2) NOT NULL DEFAULT 0,
  "cashExpenses" DECIMAL(14,2) NOT NULL DEFAULT 0,
  "cardSales" DECIMAL(14,2) NOT NULL DEFAULT 0,
  "upiSales" DECIMAL(14,2) NOT NULL DEFAULT 0
);
